name: ucard_dtc-dev-env

on:
  push:
    branches: [ develop ]

jobs:
  #Application-tests:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      node-version: [17.x]
  ##  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
   #   - uses: actions/checkout@v3
   #   - name: Use Node.js ${{ matrix.node-version }}
   #     uses: actions/setup-node@v2
   #    with:
   #       node-version: ${{ matrix.node-version }}
   #   - name: npm build and test
   #     run: |
   #       npm install
   #       npm run build --if-present
   #       npm run test  --- --- coverage
    
  Image-build:
    # needs: Application-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable dev Dockerfile
        run: mv Dockerfile-dev Dockerfile

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME_DEV }}:latest 
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME_DEV }}:v${{ github.run_number }}
          # build on feature branches, push only on main branch
          push: true
        
  Deployment:
    needs: Image-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update Image in Kubernetes Manifest
        run: sed -i "s#SAMPLE#${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME_DEV }}:v${{ github.run_number }}#g" kube-manifest/ucard_dtc-deployment-dev.yaml
      - name: Interact with cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kube-manifest/ucard_dtc-deployment-dev.yaml
